name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI and dependencies
      run: |
        pip install databricks-cli
        pip install urllib3==1.26.6 chardet==3.0.4

    - name: Configure Databricks CLI for Development
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
        echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config
        cat ~/.databricks/config

    - name: Validate Databricks CLI Configuration for Development
      run: databricks workspace list

    - name: Sync to Databricks Development
      run: databricks workspace import_dir --overwrite release /Workspace/Users/kalpesh.azure.subscription@gmail.com/release

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI and dependencies
      run: |
        pip install databricks-cli
        pip install urllib3==1.26.6 chardet==3.0.4

    - name: Configure Databricks CLI for Production
      env:
        DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
        echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config
        cat ~/.databricks/config

    - name: Validate Databricks CLI Configuration for Production
      run: databricks workspace list

    - name: Sync to Databricks Production
      run: databricks workspace import_dir --overwrite prod_release /Workspace/Users/kalpesh.azure.subscription@gmail.com/prod_release
